require('configs.melange')
require('configs.lualine')
require('configs.tree')
require('configs.treesitter')
require('configs.lsp')
require('configs.cmp')
require('configs.autopairs')
require('configs.comment')
